### PR TITLE
Fix metadata failure crashing process

### LINKED ISSUE #232: Propsd fails if it can't reach the EC2 metadata service
If I run Propsd in Vagrant, where I don't have an EC2 metadata service, I see this error in the logs.
```
{"level":"ERROR","message":"Aws-sdk returned the following error during the metadata service request to /latest/meta-data/iam/security-credentials/: {\"code\":\"ENETUNREACH\",\"errno\":\"ENETUNREACH\",\"syscall\":\"connect\",\"address\":\"169.254.169.254\",\"port\":80}","timestamp":"2017-03-29T14:19:14.567Z"}
/opt/propsd-1.5.0/lib/source/metadata/util.js:87
        const items = data.trim().split('\n');
                           ^

TypeError: data.trim is not a function
    at /opt/propsd-1.5.0/lib/source/metadata/util.js:87:28
    at ClientRequest.<anonymous> (/opt/propsd-1.5.0/lib/source/metadata.js:78:18)
    at ClientRequest.<anonymous> (/opt/propsd-1.5.0/node_modules/aws-sdk/lib/http/node.js:62:19)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1272:8)
    at nextTickCallbackWith2Args (node.js:511:9)
```

Propsd should work even if an EC2 metadata service isn't available.

### PR DESCRIPTION
**Pull request by dgreene-r7**
This PR resolves #232.

### CODE REVIEW

File: lib/source/metadata/parser.js [hunk 1]
```diff
@@ -108,6 +131,13 @@ Parser.mappings = {
   'meta-data/network/interfaces/macs/': (path, metadata, properties) => {
     const mac = metadata['meta-data/mac'];
 
+    // Return early if there's no data here
+    if (!mac) {
+      return;
+    }
+
+    properties.interface = {};
```
Comment (fmitchell-r7) [inline lib/source/metadata/parser.js]: Do you want to do
```javascript
if (!properties.interface) {
  properties.interface = {};
}
```
in case the API returns interface properties?
