### PR TITLE
Fix: refactored service list watcher and service health watcher parsing into their own classes

### LINKED ISSUE #69: Refactor Consul plugin so health watcher parsing is in its own class
Looking at the S3 plugin, it [has a parser class](https://github.com/rapid7/propsd/blob/2154e00472f33e449a128232b6075edcce97dc54/lib/source/s3.js#L9-L24) that's responsible for formatting the byte structure returned from the AWS SDK into properties. This splits the separate of concern for parsing S3 data vs. retrieving S3 data into separate classes.

The Consul plugin should be refactored so it has similar behavior. Right now the parsing logic for health watchers is [embedded in the fetch callbacks](https://github.com/rapid7/propsd/blob/2154e00472f33e449a128232b6075edcce97dc54/lib/source/consul.js#L201-L215). This should get moved into its own parser class.

### PR DESCRIPTION
**Pull request by dgreene-r7**
This PR is the first of a few to cover #103. It focuses on refactoring watcher data parsing into their own classes, prefixed with `ConquesoCompat` to indicate their intermediate status. When consul tagging is complete we can refactor that class (or create new ones that conform to the interface) to migrate to our new methodology.

This PR resolves #69 and #70.

### CODE REVIEW

File: lib/source/consul.js [hunk 1]
```diff
@@ -7,6 +7,71 @@ const consul = require('consul');
...
+  constructor() {
+    this.properties = {};
+  }
+
+  update(data, callback) {
+    const services = Object.keys(data);
+    const watcherInfo = [];
+
+    services.forEach((service) => {
+      const tags = data[service];
```
Comment (jmanero-r7) [inline lib/source/consul.js]: This doesn't solve for a tagging scheme of key-value pairs like `["version:1.2.3", "cluster:foo"]`. We need to check if there's a `key:value` format, then only pick `cluster:...`, or if there are no tags matching that format, assume that all tags are cluster names.

Comment (dgreene-r7) [inline lib/source/consul.js]: That's coming in a later PR :smile:

File: lib/source/consul.js [hunk 2]
```diff
@@ -7,6 +7,71 @@ const consul = require('consul');
 const DEFAULT_AGENT_ADDRESS = '127.0.0.1';
 const DEFAULT_AGENT_PORT = 8500;
 
+class ConquesoCompatHealthParser {
+  constructor() {
+    this.properties = {};
+  }
+
+  update(data, cluster) {
```
Comment (fmitchell-r7) [inline lib/source/consul.js]: Would you be willing to put in API docs around the `update` method?

File: lib/source/consul.js [hunk 3]
```diff
@@ -7,6 +7,71 @@ const consul = require('consul');
...
+    this.properties = properties;
+  }
+}
+
+class ConquesoCompatServiceParser {
+  constructor() {
+    this.properties = {};
+  }
+
+  update(data, callback) {
```
Comment (fmitchell-r7) [inline lib/source/consul.js]: Would you be willing to put in API docs around the `update` method?

**Comment by fmitchell-r7** [comment]
:+1: Thanks for doing this refactor! This should resolve #69 and #70 as well. :shipit:
