### PR TITLE
Fix: Remove translated Consul properties

### LINKED ISSUE #90: Remove translated Consul plugin properties from Conqueso output
The Conqueso API [translates Consul plugin output](https://github.com/rapid7/propsd/blob/master/lib/control/v1/conqueso.js#L26-L54) into Conqueso compatible output. We should remove the `consul.` output that was translated so it doesn't show up in the final properties set. This will avoid exposing Conqueso clients to properties they don't care about.

### PR DESCRIPTION
**Pull request by fmitchell-r7**
This fixes #90. Consul properties that have been translated into the Conqueso compatibility layer are removed from the formatted output.

### CODE REVIEW

**Comment by dgreene-r7** [comment]
:+1:

**Comment by jmanero-r7** [comment]
Please hold

File: lib/control/v1/conqueso.js [hunk 1]
```diff
@@ -48,6 +49,7 @@ function injectConquesoAddresses(properties) {
 
       conquesoIps[`conqueso.${cluster}.ips`] = properties.consul[service].addresses.join(',');
     });
+    delete properties.consul; // eslint-disable-line no-param-reassign
```
Comment (jmanero-r7) [inline lib/control/v1/conqueso.js]: It looks like `properties` a reference to the object managed by the Storage module. Mutating it here is likely to have strange effects on other consumers that expect it's `consul` key to not disappear whenever this handler is executed.

We should do something like this insterad:

```
// Construct a new Object with only 'conqueso.SERVICE.ips=list,of,addresses` key/values
const conquesoIps = translateConquesoAddresses(properties);

const conquesoProperties = Object.assign({}, properties, conquesoIps);
delete conquesoProperties.consul;

makeJavaProperties(flatten(conquesoProperties));
...
```

**Comment by jmanero-r7** [comment]
Looks good :+1:
